# Generated by Django 5.0 on 2025-10-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pexels_id', models.CharField(db_index=True, max_length=50)),
                ('photographer', models.CharField(max_length=255)),
                ('tags', models.TextField(help_text='Tags associadas à imagem (separadas por vírgula)')),
                ('original_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
